name: Build Android APK (Kivy/Buildozer)

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.py'
      - 'buildozer.spec'
      - '.github/workflows/android-build.yml'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Run the official Buildozer image directly as root to avoid chown/user issues
      - name: Build APK with Docker (root)
        run: |
          docker run --rm \
            -e BUILDOZER_WARN_ON_ROOT=1 \
            -v "$PWD":/work \
            -w /work \
            ghcr.io/kivy/buildozer:stable \
            buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
