name: Build Android APK (Kivy/Buildozer)

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.py'
      - 'buildozer.spec'
      - '.github/workflows/android-build.yml'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk zip unzip \
            libffi-dev libssl-dev libsqlite3-dev zlib1g-dev \
            libjpeg-dev libfreetype6-dev \
            autoconf automake libtool pkg-config \
            build-essential python3-dev

      - name: Install Buildozer (no Docker)
        run: |
          python -m pip install --upgrade pip
          # Pin Cython < 3 for maximum compatibility with python-for-android
          pip install "cython<3" buildozer

      - name: Build debug APK
        env:
          # Avoid interactive prompts
          BUILDOZER_WARN_ON_ROOT: "0"
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
